[[headers]]
  for = "*"
  [headers.values]
    Access-Control-Allow-Origin = "https://editof.site"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"